linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - exhaustive
    - noctx
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
    - source: "log\\.Print"
      linters: [errcheck]
    - path: internal/services/share\.go
      linters: [noctx]
    - source: "func.*withSender"
      linters: [unused]
